### ISSUE TITLE
Change use of System.Random to Verse.Rand for compatibility with Multiplayer

### ISSUE THREAD

**Issue by ghost** [Syrchalis/SetUpCamp#7]
For instance, here: https://github.com/Syrchalis/SetUpCamp/blob/9d0521a8534ccb81cb964b9ebe7454390f0a1460/Source/SetupCamp/SetUpCampCore.cs#L142

The Multiplayer mod will desync when System.Random or Unity.Random is used because there's no way to prevent clients from receiving a different results. However, Multiplayer is able to encapsulate the use of Verse.Rand.

**Comment by Syrchalis** [comment]
Fixed.
